# Reset newline settings
add_newline = false
[line_break]
disabled = false

# Custom format to show info on top line and prompt below
format = """
$all
$character"""

# Configure the prompt character to start at the beginning of the line
[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

# Keep package module disabled
[package]
disabled = true
